CREATE TABLE users (
iduser INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
fullname VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
usertype VARCHAR(50) NOT NULL,
passwd VARCHAR(20) NOT NULL);

CREATE TABLE departamento (
iddepto INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
deptoname VARCHAR(20) NOT NULL);